apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: userprofile-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VishwanathMalide/Shine-GitOps-Project.git
    targetRevision: main
    path: Retail-chart
    helm:
      values: |
        userprofile:
          activeVersion: blue
  destination:
    server: https://vishwanath-test-cluster-dns-k6dgfwge.hcp.canadacentral.azmk8s.io:443
    namespace: retail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
